# SSL/HTTPS Override for Production
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ssl.yml up

services:
  frontend:
    # Ensure we're using the production nginx image, not dev server
    image: tc-mgr-frontend:latest
    build:
      target: production
    ports:
      - "443:443"  # Only expose HTTPS, nginx handles HTTP->HTTPS redirect internally
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./frontend/nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx-base.conf:/etc/nginx/nginx.conf:ro
    environment:
      - ENABLE_SSL=true
    # Override any development command/entrypoint
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: []

volumes:
  ssl_certs:
    driver: local
