# SSL/HTTPS Override for Production
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ssl.yml up

services:
  frontend:
    ports:
      - "8090:80"
      - "8443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./ssl/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - ENABLE_SSL=true

volumes:
  ssl_certs:
    driver: local
